# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171028_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='key',
            field=models.CharField(default='server', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
